# Generated by Django 5.0.2 on 2024-03-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_autor"),
    ]

    operations = [
        migrations.CreateModel(
            name="Livro",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="autor",
            name="email",
            field=models.CharField(max_length=100),
        ),
    ]
