# Generated by Django 5.1 on 2024-08-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_autor_options_livro_autores"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="livro",
            name="autores",
        ),
        migrations.AddField(
            model_name="livro",
            name="autor",
            field=models.ManyToManyField(blank=True, related_name="livros", to="core.autor"),
        ),
    ]
